name: Release

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Prepare repository
              run: git fetch --unshallow --tags

            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build
              run: yarn build-storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./storybook-static
